#!/bin/bash

set -e

# This shell script runs all of the WORKING tests that PASS.
# It will also remove all of the temporary files that are generated by the test
# cases.
# If any of the tests in this script FAIL, DO NOT PUSH YOUR CHANGES TO THE
# GITHUB REPOSITORY!

echo "./bin/unittest-deviceVector"
./bin/unittest-deviceVector

echo "./bin/unittest-charmmPSF"
./bin/unittest-charmmPSF

echo "./bin/unittest-noseHoover"
./bin/unittest-noseHoover

echo "./bin/unittest-langevinPiston"
./bin/unittest-langevinPiston

echo "./bin/unittest-langevinThermostat"
./bin/unittest-langevinThermostat

echo "./bin/unittest-restartSubscriber"
./bin/unittest-restartSubscriber

echo "./bin/unittest-restraintForce"
./bin/unittest-restraintForce

# unittest-noseHoover
rm -rf waterbox_1_s_new.dcd waterbox_1_s_old.dcd

# unittest-restart
rm -rf tmpNoseHoover.rst tmpLangevinPiston.rst tmpLangevinThermostat.rst
